[package]
name = "agni-harden"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1"
radix-wasm-instrument = "=1.0.0"
serde = { version = "1", features = ["derive"] }
spirit-sdk = { git = "https://git.rae.blue/abysl/spirit-library" }
wasm-encoder = "=0.29.0"
wasmparser = "=0.107.0"

[dev-dependencies]
wasmi = "1"
wat = "1"

[lib]
name = "agni_harden"

[[bin]]
name = "agni-harden"
path = "src/main.rs"
